### ISSUE TITLE
can Cephei replaced with libsandy?

### ISSUE THREAD

**Issue by Mabdelwanis** [yandevelop/Stella#1]
hello dear thanks for amazing tweak 
i missed this tweak in dopamine since Cephei not yet updated to support rotless. any chance to make this tweak work for rootles ?
Greetings

**Comment by yandevelop** [comment]
libSandy is something different and not needed for this tweak. As soon as Cephei is updated, Stella will receive support for rootless :)

**Comment by Mabdelwanis** [comment]
thanks there's new beta version of cephei released can you check this out

**Comment by yandevelop** [comment]
Thanks for letting me know. I'll provide an update asap
